services:
  # PhantomCopeService
  # ファントムの追跡から逃れるための機能まとめ
  phantomCopeService:
    items:
      - name: ROTTEN_FLESH # ゾンビ肉
        ticks: 1200 # 20tick/1s * 60s
      - name: POISONOUSE_POTATO # 青芋
        ticks: 1200
    messages:
      activation: null
      deactivation: null