services:
  # PhantomCopeService
  # ファントムの追跡から逃れるための機能まとめ
  phantomCopeService:
    items:
      - name: ROTTEN_FLESH # ゾンビ肉
        ticks: 1000
      - name: POISONOUSE_POTATO # 青芋
        ticks: 1000
    messages:
      activation: null
      deactivation: null