services:
  # PhantomCopeService
  # ファントムの追跡から逃れるための機能まとめ
  phantomCopeService:
    items:
      - name: ROTTEN_FLESH # ゾンビ肉
        ticks: 1200 # 20tick/1s * 60s
      - name: POISONOUS_POTATO # 青芋
        ticks: 1200
    messages:
      activation: null # $ticks を有効時間に置き換える
      deactivation: null
    ignore-item-effect: true # 消費したアイテムの本来の効果を無視する
    cancel-indoor: true # 屋内でのスポーンをキャンセルするか
    max-altitude: 256 # 屋内かの判定を高度どこまで行うか

  # DragonHeadService
  dragon-head:
    is-trigger-fire: false
    explosive-radius: 0.0
    cool-time: 20
    fireball-speed: 1
    enable-jetpack: true
    multiply-jetpack: 1.0