services:
  # PhantomCopeService
  # ファントムの追跡から逃れるための機能まとめ
  phantomCopeService:
    items:
      - name: ROTTEN_FLESH # ゾンビ肉
        ticks: 1200 # 20tick/1s * 60s
      - name: POISONOUS_POTATO # 青芋
        ticks: 1200
    messages:
      activation: null
      deactivation: null
    ignore-item-effect: true # 消費したアイテムの本来の効果を無視する
