name: IntegrativeYmzeServerPlugin
version: 0.0.1
main: dev.ekuinox.IntegrativeYmzeServerPlugin.Main
api-version: "1.15"
description: "やまぞえサーバにようこそ"
commands:
  ymze:
    description: "やまぞえサーバにようこそ"
    usage: /ymze
permissions:
  ymze.*:
    default: op
