name: IntegrativeYmzeServerPlugin
version: 0.0.1
main: dev.ekuinox.IntegrativeYmzeServerPlugin.Main
api-version: "1.15"
description: "やまぞえサーバにようこそ"
commands:
  ymze:
    description: "やまぞえサーバにようこそ"
    usage: /ymze
permissions:
  ymze.*:
    default: op
    children:
      ymze.phantomcoping: true
      ymze.central.reload: true
  ymze.phantomcoping:
    default: true
    description: Player can cope phantoms by consuming rotten flesh
  ymze.central.reload:
    default: op
    description: reload config.yml
